// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4VVAA6Npkc5xdP64C0Cr1WGQjU1xSKBM',
    appId: '1:734280454164:web:7a6aff8a7b8fa36d819701',
    messagingSenderId: '734280454164',
    projectId: 'phone-store-new',
    authDomain: 'phone-store-new.firebaseapp.com',
    storageBucket: 'phone-store-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsGHVJzmam_80J1eSh2JzoVa7fialGCVs',
    appId: '1:734280454164:android:f3c7c785686e7ef3819701',
    messagingSenderId: '734280454164',
    projectId: 'phone-store-new',
    storageBucket: 'phone-store-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5msK7oDG-6yc1MGKUdiwt-O5hyJc2ZgM',
    appId: '1:734280454164:ios:d7be5b7fdf03d1fe819701',
    messagingSenderId: '734280454164',
    projectId: 'phone-store-new',
    storageBucket: 'phone-store-new.firebasestorage.app',
    iosBundleId: 'com.example.phoneStore',
  );
}
